### ISSUE TITLE
Configurable SendToUI Pipeline

### ISSUE THREAD

**Issue by FrancescoZ** [elixir-crawly/crawly#152]
It would be nice to be able to select the module and the function to which the data is sent when doing 
```
:rpc.cast(ui_node, CrawlyUI, :store_item,
```
 is it something you could be interested in?
For context:
I'm using crawly to scan amazon, on top of it I've added something similar to `CrawlyUI` and I would like to send the item to that module. I workaround it by having a module called CrawlyUI that can handle the call but I would be nice to add it in the config

**Comment by oltarasenko** [comment]
Yes, I think it should be fine to do that. However, if the configuration is not set the pipeline should probably default to the CrawlyUI..

**Comment by FrancescoZ** [comment]
I will try to open a pull request this weekend

**Comment by FrancescoZ** [comment]
@oltarasenko can you give me the permission to push to the repo 🙏 ?

**Comment by oltarasenko** [comment]
Invite sent.
