### ISSUE TITLE
curl fetcher

### ISSUE THREAD

**Issue by dkuku** [elixir-crawly/crawly#181]
there is a bug in hackney which prevents me from using httppotion, I can use the splash fetcher just fine.
But it seems heavy so I created a simple fetcher that uses curl. It probably can be extended and added to the repo.
In the config its just `fetcher: {Crawlers.Curl, []},`   
```elixir
defmodule Fetchers.Curl do
  def fetch(request, options) do
    case System.cmd("curl", [request.url, "-s"] ++ options) do
      {body, 0} ->
        {:ok,
         %HTTPoison.Response{
           body: body,
           headers: [],
           request: request,
           request_url: request.url,
           status_code: 200
         }}
      error ->
        IO.inspect(error)
        {:error, :failed}
    end
  end
end


```

**Comment by Ziinc** [comment]
I think that we would not be supporting this, as it adds additional maintenance burden.

A contribution to the docs under custom fetchers would be welcomed, if you'd like to share your specific use case @dkuku
