### ISSUE TITLE
Suggestion for nameing of closespider_timeout in config 

### ISSUE THREAD

**Issue by EdmondFrank** [elixir-crawly/crawly#183]
![image](https://user-images.githubusercontent.com/13914416/116493021-6371d300-a8d0-11eb-85c6-a773bba0d207.png)

It seems that when all the workers’ requests list are empty, the crawler still cannot stop automatically.

Maybe it is more convenient  to determine when the spider need be stopped by providing a optional item `closespider_deltacount` with default value `0`  in config

**Comment by EdmondFrank** [comment]
This issue can be solved by setting `closespider_timeout: 0`

But I feel that the name of this settings item is confusing.

It is easy to misunderstand that this is a setting about the timeout of network requests

Maybe `closespider_min_delta` is better, this is just my personal suggestion.

**Comment by Ziinc** [comment]
I see, yes, setting naming is an issue, but that's what the docs are for :sweat_smile:  Interesting that the spider doesn't auto close when there isn't any requests in the queue, might be an issue with default config.
