### ISSUE TITLE
Generic `Pipeline crash` error

### ISSUE THREAD

**Issue by thiagomajesk** [elixir-crawly/crawly#185]
Hi, I'm getting a generic [pipeline crash](https://github.com/elixir-crawly/crawly/blame/60c5e1ab33915d4e6ec7652ca3b34793b5031077/lib/crawly/utils.ex#L96) error on the current release.

It seems though that this [was solved](https://github.com/elixir-crawly/crawly/blame/master/lib/crawly/utils.ex#L107) on the `master` branch 3 months ago. Any plans to release a new patch version for this?

I tested running on `master`, but I don't feel comfortable enough depending on an edge version. Right now I have to switch back and forth whenever I have a problem in the pipelines I want to debug.

PS.: Thanks for the awesome work in this lib guys. It's really really cool!

**Comment by Ziinc** [comment]
going to let @oltarasenko decide on the new release :slightly_smiling_face:

**Comment by KristerV** [comment]
I know +1 isn't welcome on GitHub generally, but since there are so few people here... +1 :)

**Comment by Rodeoclash** [comment]
+1 here as well :/
