### ISSUE TITLE
Could not compile dependency :epipe

### ISSUE THREAD

**Issue by avillen** [elixir-crawly/crawly#190]
Hi! :wave: I'm having issues compiling the dependency from my project and also downloading the repo with current master:

```
** (Mix) Could not compile dependency :epipe, "/home/av/.asdf/installs/elixir/1.10.3-otp-23/.mix/rebar3 bare compile --paths="/home/av/OSS/crawly/_build/test/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile epipe", update it with "mix deps.update epipe" or clean it with "mix deps.clean epipe"
```

No one of the error suggestions works for me. Is this a real problem or is it only happening to me? :sweat_smile: 

I think that the only place where this dependency is used is here: https://github.com/elixir-crawly/crawly/blob/b6e833fc50008f339247c52c58ab5c641bf746bf/lib/crawly/worker.ex#L53

What I was thinking is that if the only intention of this is to iterate over the list of functions, apply them in order and stop if any of them fails, maybe we can get rid of it and use plain elixir. If you agree with this I can take care of it and send a PR with a proposal :smile:

Also, even removing the `:epipe` dependency, I need to run `mix deps.update cowboy_telemetry` in order to compile the project. Does this makes sense for you? Or am I doing something strange?

Thanks in advanced!

**Comment by Ziinc** [comment]
@avillen yes, it is possible to replace it with a `with...do`, but we haven't gotten round to it yet. A PR would be great, I can help review.

**Comment by Ziinc** [comment]
regarding the `cowboy_telemetry` update, could you let me know your elixir/otp version number, i'll try to replicate it

**Comment by Ziinc** [comment]
is it `1.10.3-otp-23` ?

**Comment by avillen** [comment]
:wave: Hi @Ziinc 

> is it `1.10.3-otp-23` ?

Yes! but upgrading dependencies solves the issue :smile: 

> @avillen yes, it is possible to replace it with a `with...do`, but we haven't gotten round to it yet. A PR would be great, I can help review.

I just have pushed a PR for this, let me know if it looks good for you!

**Comment by avillen** [comment]
Closing this issue now that this gets merged https://github.com/elixir-crawly/crawly/pull/192. Thanks a lot! 😄
