### ISSUE TITLE
Demo page not loading

### ISSUE THREAD

**Issue by braynm** [elixir-crawly/crawly#198]
It seems like the [demo page](http://crawlyui.com/) is not working correctly (The connection has timed out). Please see the screenshot below.

![Screen Shot 2021-10-11 at 11 34 49 AM](https://user-images.githubusercontent.com/1388366/136729658-2ab014b5-53a5-4ef0-8df8-357ebc3dd99c.png)

**Comment by joao2391** [comment]
Same here.

**Comment by oltarasenko** [comment]
I have stopped active development of CrawlyUI, and don't have enough money to have a standalone server. So will not work on this.

**Comment by oltarasenko** [comment]
I have stopped active development of CrawlyUI, and don't have enough money to have a standalone server. So will not work on this.
