### ISSUE TITLE
Any working examples?

### ISSUE THREAD

**Issue by dogweather** [elixir-crawly/crawly#210]
I've tried many tutorials and demos, but none of them have worked for me. Either it appears to run but I get no output file, or a puzzling `function Crawly.fetch/1 is undefined or private`.

I'm using elixir 1.13.4-otp-24 and erlang 24.3.4.2. (Not using 25 because it's not compatible with the Elixir LS / VS Code extension.)

Can someone point to verified-working demo code?

I'm really intrigued by Crawly, and have a large Scrapy project I'd consider migrating from.

**Comment by oltarasenko** [comment]
Could you please try an example in the examples folder of the project? It is supposed to work

**Comment by dogweather** [comment]
> Could you please try an example in the examples folder of the project? It is supposed to work

Yep, giving it a shot now.

**Comment by dogweather** [comment]
Yes, it definitely worked. Thank you. I followed the instructions from the main README for it. I got the results in `/tmp` as promised.

**Comment by dogweather** [comment]
All the tests passed for me too - the framework's as well as the examples. In the framework, I'm using asdf to provide:

```
elixir 1.14.0-otp-24
erlang 24.3.4.2
```

**Comment by oleg-kivra** [comment]
I will close the ticket for now, and will try to add more examples into the examples folder
