### ISSUE TITLE
robots.txt matching is pretty buggy

### ISSUE THREAD

**Issue by serpent213** [elixir-crawly/crawly#254]
@oltarasenko I just noticed you are maintaining your own fork of [Gollum](https://github.com/elixir-crawly/gollum). I found its matching algorithm having some severe bugs and also feels hard to reason about.

Just wanted to draw your attention to two [pull](https://github.com/ravern/gollum/pull/3) [requests](https://github.com/ravern/gollum/pull/5), which introduce additional tests.

Might rewrite the matcher, but first things first.

**Comment by oltarasenko** [comment]
@serpent213 yeah, I forked the Gollum a few years ago due to the same reason. I had the plan to fix the parsing there but did not have enough time to do that. Unfortunately :(.

**Comment by fstp** [comment]
Hi,

I would like to pick this task and start improving the parser if that is okay.
@serpent213  could you resubmit your pull request to the forked repo from oltarasenko?
(https://github.com/elixir-crawly/gollum)

After it has been merged we can start to work on improving the parser in that fork since it seems like the original project is abandoned by now.

**Comment by oltarasenko** [comment]
@fstp Please let me know if I can help you in any way.

**Comment by serpent213** [comment]
@fstp See https://github.com/elixir-crawly/gollum/pull/1.

**Comment by fstp** [comment]
Thank you for the quick response! :)
@oltarasenko if you want you could merge the pull request from @serpent213 and then I can create my pull request based on that. Or is it better that I push directly to the pull request?

**Comment by serpent213** [comment]
One of the commits introduces a failing test, IIRC. The Google-port has a lot of stuff commented out to pass.

**Comment by fstp** [comment]
Ah okay I see, can I clone your pull request somehow and push the code directly there? Would be nice to run test driven development against the failing testcases

**Comment by serpent213** [comment]
Maybe you can start your own branch and cherry-pick the commits?

**Comment by fstp** [comment]
Thanks! I will try to work directly on your fork, seems most convenient since we can just merge it all together then :)
