### ISSUE TITLE
Make the management tool opt-in by default

### ISSUE THREAD

**Issue by aej** [elixir-crawly/crawly#262]
I think it would be more convenient for the management tool to be removed by default from the application children and instead make it opt-in. 

This would let library users who do not want to run the management tool at all, or who want to run the management tool in a different place (i.e inside another Plug-based application/supervision tree) be able to do so without unnecessarily running a webserver.

We can then instruct library users to simply add the `Crawly.API.Router` to their supervision tree with whatever configuration/plug-compatible webserver they choose.

```elixir
# application.ex
defmodule MyApp.Application do
  use Application


  def start(_) do
    children = [
      ...
      {Plug.Cowboy, scheme: :http, plug: Crawly.API.Router}
      ...
    ]
  end
end
```

**Comment by oltarasenko** [comment]
I like the idea!

**Comment by samullen** [comment]
Any chance of getting this released soon? Pretty please?

**Comment by oltarasenko** [comment]
Yes sure. There is no reason to keep it unreleased. let me prepare the release early this week
