### ISSUE TITLE
Upgrade to `httpoison` 2.x?

### ISSUE THREAD

**Issue by samrat** [elixir-crawly/crawly#276]
Hello,

I'm using `crawly` in a project where I also depend on httpoison 2.0. Because crawly depends on httpoison 1.7, this creates a conflicting dependency.

Are there plans of upgrading httpoison to 2.0?

**Comment by brandonparsons** [comment]
Is there a branch for this I can use in the meantime?

**Comment by oltarasenko** [comment]
https://github.com/elixir-crawly/crawly/pull/293
