### ISSUE TITLE
Does Crawly support requests using the POST method?

### ISSUE THREAD

**Issue by oallanmendes** [elixir-crawly/crawly#281]
I've encountered a challenge related to passing the "next_requests" using the POST method. It appears that Crawly.Request doesn't have built-in support for handling HTTP methods. Could someone kindly assist me in resolving this issue?

**Comment by zastrixarundell** [comment]
The only thing I can think of is probably setting a custom fetcher which can either do post or get methods. You can look at [this implementation](https://github.com/elixir-crawly/crawly/blob/master/lib/crawly/fetchers/httpoison_fetcher.ex) for it. The second argument regarding the request is only set on during the config phase so it's not something you can specify in your crawler.
