### ISSUE TITLE
CI issue: Failed to upload the report to 'https://coveralls.io', Couldn't find a repository matching this job.

### ISSUE THREAD

**Issue by OldhamMade** [elixir-crawly/crawly#288]
```
Failed to upload the report to 'https://coveralls.io' (reason: status_code = 422, 
body = {"message":"Couldn't find a repository matching this job.","error":true})
```
[Report link](https://app.circleci.com/pipelines/github/elixir-crawly/crawly/302/workflows/f1a16299-1880-4f9e-9bc5-a3f166f16211/jobs/358)

**Comment by oltarasenko** [comment]
I have removed circle and coveralls, as I was seeing quite a few errors like that. Github actions seem to work better.
